"""SIM Realisasi data model: tables, columns and relationships, transcribed from supabase/migrations.

Used by generate.py to render the ERD and the data dictionary. Keep in step with 0001_kerjasama_adapter.sql and
0002_tables.sql when the schema changes.

Column tuple: (name, type, key, nullable, description)
  key: "PK", "FK", "UQ", "PK FK", "LFK" (logical reference to a kerjasama.* view or mock registry; no database FK)
"""

DOMAINS = {
    "simks": "SIM Kerjasama (read-only adapter views)",
    "activity": "Kegiatan (activity)",
    "participant": "Peserta & verifikasi mobilitas",
    "calendar": "Kalender, konfigurasi & RENSTRA",
    "ops": "Operasional & registri mock",
}

# (schema.table, domain, column, purpose, columns)
TABLES = [
    # ------------------------------------------------------------------ SIM Kerjasama views
    ("kerjasama.profiles", "simks", 0, "User accounts (SIMKS akun) that have a Realisasi role. View; id is the Supabase Auth user id.", [
        ("id", "uuid", "PK", False, "Auth user id, or a stable uuid derived from the akun id."),
        ("email", "text", "", False, "Login email (role-based unit address for submitters)."),
        ("display_name", "text", "", False, "Position name (jabatan) or email."),
        ("app_role", "text", "", True, "submitter | io_staff | io_admin | viewer; null when the akun is inactive."),
        ("unit_id", "int", "LFK", True, "Unit of the account (account_roles override, else jabatan unit)."),
        ("akun_id", "int", "", False, "SIMKS akun.id."),
        ("auth_user_id", "uuid", "", True, "Supabase Auth user, when linked."),
    ]),
    ("kerjasama.units", "simks", 0, "Organisational units. Only academic units (is_academic) submit kegiatan (R-06a).", [
        ("id", "int", "PK", False, "SIMKS unit.id."),
        ("name", "text", "", False, "Unit name."),
        ("parent_id", "int", "", True, "Parent unit."),
        ("kind", "text", "", False, "up | faculty | prodi, derived from jenis_unit and hierarchy."),
        ("is_active", "boolean", "", False, "Active in SIMKS."),
        ("is_academic", "boolean", "", False, "jenis_unit = Unit Akademik."),
    ]),
    ("kerjasama.agendas", "simks", 0, "Agenda Kerjasama list, used as Jenis Kegiatan (amendment excluded).", [
        ("id", "int", "PK", False, "SIMKS agenda.id."),
        ("name", "text", "", False, "Agenda name shown as Jenis Kegiatan."),
        ("is_active", "boolean", "", False, "Selectable for new kegiatan."),
    ]),
    ("kerjasama.documents", "simks", 0, "MoU/MoA documents (one per dokumen_kerja_sama). Renewal chains follow predecessor_id.", [
        ("id", "int", "PK", False, "dokumen_kerja_sama.no."),
        ("doc_number", "text", "", False, "Document number, or 'Tanpa nomor #n'."),
        ("title", "text", "", False, "First line of tujuan_kerjasama, else kind + lead partner."),
        ("kind", "text", "", False, "MoU / MoA / IA etc. (jenis_kerjasama)."),
        ("status", "text", "", False, "active | archived | rejected | in_process. Rejected and in-process are never selectable (R-04)."),
        ("start_date", "date", "", True, "Validity start."),
        ("end_date", "date", "", True, "Validity end."),
        ("auto_renewed", "boolean", "", False, "From document_overrides; auto-renewed chains skip the grace exclusion (R-43)."),
        ("predecessor_id", "int", "LFK", True, "Previous document in the renewal chain."),
        ("archived_reason", "text", "", True, "rejected | superseded_by_renewal | expired_without_renewal."),
        ("terminated_at", "timestamptz", "", True, "From document_overrides."),
        ("proposal_id", "int", "", False, "SIMKS proposal_dokumen.id."),
        ("simks_status", "text", "", True, "Raw SIMKS status text."),
    ]),
    ("kerjasama.document_partners", "simks", 0, "Partners named on each document.", [
        ("document_id", "int", "LFK", False, "Document."),
        ("partner_id", "int", "LFK", False, "Partner."),
        ("is_lead", "boolean", "", False, "Lead partner of the proposal."),
    ]),
    ("kerjasama.document_scope_units", "simks", 0, "Lingkup Kerja Sama: units covered by a document. Outside scope = warning (R-05).", [
        ("document_id", "int", "LFK", False, "Document."),
        ("unit_id", "int", "LFK", False, "Unit in scope."),
    ]),
    ("kerjasama.partners", "simks", 0, "Partner institutions.", [
        ("id", "int", "PK", False, "SIMKS partner.id."),
        ("name", "text", "", False, "Partner name."),
        ("country_code", "text", "LFK", True, "ISO alpha-2; 'ID' for domestic partners without a mappable country."),
        ("merged_into_id", "int", "", True, "Partner this one was merged into."),
        ("is_active", "boolean", "", False, "Active in SIMKS."),
    ]),
    ("kerjasama.countries", "simks", 0, "Countries mapped from SIMKS negara to ISO 3166.", [
        ("code", "text", "PK", False, "ISO alpha-2."),
        ("name", "text", "", False, "Country name."),
        ("alpha3", "text", "", False, "ISO alpha-3."),
        ("negara_id", "int", "", False, "SIMKS negara.id."),
        ("is_domestic", "boolean", "", False, "Indonesia."),
    ]),

    # ------------------------------------------------------------------ bridging + activity
    ("realisasi.account_roles", "simks", 1, "Grants a SIMKS akun access to Realisasi with a role (feeds kerjasama.profiles).", [
        ("akun_id", "int", "PK", False, "SIMKS akun.id."),
        ("app_role", "text", "", False, "submitter | io_staff | io_admin | viewer."),
        ("unit_id", "int", "LFK", True, "Unit override for the account."),
        ("updated_at", "timestamptz", "", False, "Last change."),
    ]),
    ("realisasi.activity_units", "activity", 1, "Units involved in a kegiatan: the submitter plus co-units (read-only access, R-14).", [
        ("activity_id", "uuid", "PK FK", False, "Kegiatan."),
        ("unit_id", "int", "PK LFK", False, "Academic unit."),
        ("is_submitter", "boolean", "", False, "True for the submitting unit."),
    ]),
    ("realisasi.agenda_rules", "calendar", 1, "Counting rule per Jenis Kegiatan (R-07a). No row or null category = non-mobility.", [
        ("agenda_id", "int", "PK LFK", False, "Agenda (Jenis Kegiatan)."),
        ("mobility_category", "mobility_category", "", True, "jd_dd | student_exchange | short_summer | other_mobility; null = not mobility."),
        ("counts_for_s1", "boolean", "", False, "Counts for RENSTRA 1.19.S1. Default true."),
        ("updated_by", "uuid", "LFK", True, "IO Admin who edited it."),
        ("updated_at", "timestamptz", "", True, "Last change."),
    ]),
    ("realisasi.activity_documents", "activity", 1, "The one agreement a kegiatan implements (R-03). Stores the original document; the current one is resolved via the chain.", [
        ("activity_id", "uuid", "PK FK UQ", False, "Kegiatan (unique: one agreement per kegiatan)."),
        ("original_document_id", "int", "PK LFK", False, "Document picked at submission."),
        ("chain_id", "int", "", False, "Root of the renewal chain; RENSTRA 1.19.24 counts chains (R-42)."),
        ("out_of_scope_warning", "boolean", "", False, "Submitting unit not in Lingkup Kerja Sama (R-05)."),
    ]),
    ("realisasi.document_overrides", "simks", 1, "Realisasi-only document facts SIMKS lacks, joined into kerjasama.documents.", [
        ("document_id", "int", "PK LFK", False, "dokumen_kerja_sama.no."),
        ("auto_renewed", "boolean", "", False, "Auto-renewing agreement."),
        ("terminated_at", "timestamptz", "", True, "Early termination."),
        ("note", "text", "", True, "Why the override exists."),
        ("updated_at", "timestamptz", "", False, "Last change."),
    ]),
    ("realisasi.activity_partner_snapshot", "activity", 1, "Partner name and country frozen at link time (R-06).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("activity_id", "uuid", "FK", False, "Kegiatan."),
        ("document_id", "int", "LFK", False, "Document the partner came from."),
        ("partner_id", "int", "LFK", False, "Partner."),
        ("partner_name", "text", "", False, "Name as captured."),
        ("country_code", "text", "", False, "Alpha-2 as captured; ≠ ID makes the kegiatan international."),
        ("captured_at", "timestamptz", "", True, "Capture time."),
    ]),
    ("realisasi.activity_sdgs", "activity", 1, "SDGs a kegiatan supports.", [
        ("activity_id", "uuid", "PK FK", False, "Kegiatan."),
        ("sdg_id", "smallint", "PK FK", False, "SDG 1–17."),
    ]),
    ("realisasi.sdgs", "calendar", 1, "Sustainable Development Goals master.", [
        ("id", "smallint", "PK", False, "1–17."),
        ("name", "text", "", False, "Indonesian name."),
    ]),
    ("realisasi.activity_external_persons", "activity", 1, "Foreign speakers, visiting lecturers and guests. Not counted in RENSTRA 1.1 (R-20).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("activity_id", "uuid", "FK", False, "Kegiatan."),
        ("full_name", "text", "", False, "Name."),
        ("institution", "text", "", False, "Home institution."),
        ("country_code", "text", "LFK", False, "Alpha-2."),
        ("role", "person_role", "", False, "speaker | visiting_lecturer | researcher | staff_visitor | other."),
        ("notes", "text", "", True, "Free text."),
    ]),
    ("realisasi.activity_files", "activity", 1, "IA, IR, mobility PDF and evidence, versioned (R-13).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("activity_id", "uuid", "FK", False, "Kegiatan."),
        ("kind", "file_kind", "", False, "ia | ir | mobility_bundle | evidence."),
        ("version", "int", "", False, "Version number, default 1."),
        ("storage_path", "text", "", True, "Path in file storage (one of path or url required)."),
        ("url", "text", "", True, "Link for evidence."),
        ("filename", "text", "", True, "Original filename."),
        ("size_bytes", "int", "", True, "Size; max 10 MB."),
        ("mime", "text", "", True, "PDF for IA/IR/mobility; PDF/JPG/PNG for evidence."),
        ("is_current", "boolean", "", False, "Current version. Unique per kegiatan for ia, ir, mobility_bundle."),
        ("uploaded_by", "uuid", "LFK", True, "Uploader."),
        ("uploaded_at", "timestamptz", "", True, "Upload time."),
    ]),

    ("realisasi.activities", "activity", 2, "One realization (kegiatan) of an agreement: one IA and one IR (R-02). Status is derived (R-25).", [
        ("id", "uuid", "PK", False, "Row id."),
        ("code", "text", "UQ", False, "Human code RL-YYYY-nnnn."),
        ("name", "text", "", False, "Nama Kegiatan."),
        ("agenda_id", "int", "LFK", False, "Jenis Kegiatan (kerjasama.agendas); rule in agenda_rules."),
        ("direction", "direction", "", False, "inbound | outbound (R-07b)."),
        ("start_date", "date", "", False, "Tanggal Mulai; the activity date for counting (R-36)."),
        ("end_date", "date", "", False, "Tanggal Selesai; ≥ start and ≤ today (R-08)."),
        ("academic_year_id", "int", "FK", True, "Derived from start_date (R-09)."),
        ("semester_id", "int", "FK", True, "Derived from start_date (R-09)."),
        ("mode", "activity_mode", "", False, "offline | online | hybrid."),
        ("venue", "text", "", True, "Tempat pelaksanaan or online platform."),
        ("country_code", "text", "LFK", True, "Country where it took place; ID drives Outbound Dalam Negeri."),
        ("sks_recognized", "numeric(4,1)", "", True, "SKS diakui; mobility only."),
        ("description", "text", "", False, "Deskripsi."),
        ("submitter_unit_id", "int", "LFK", False, "Submitting academic unit."),
        ("created_by", "uuid", "LFK", False, "Account that created it."),
        ("submitted_at", "timestamptz", "", True, "First Ajukan."),
        ("verified_at", "timestamptz", "", True, "First time verified; never changed by later edits (R-28)."),
        ("status", "activity_status", "", False, "draft | in_verification | revision_requested | verified."),
        ("mobility_status", "track_status", "", False, "not_required | pending | revision_requested | approved."),
        ("mobility_since", "timestamptz", "", True, "Last mobility-track change; drives revision reminders."),
        ("event_group_id", "uuid", "FK", False, "Event group (one per kegiatan since Revisi V.1, R-32)."),
        ("reporting_deadline", "date", "", True, "end_date + reporting_deadline_days (R-10)."),
        ("is_late", "boolean", "", False, "Submitted after the deadline (Terlambat)."),
        ("created_at", "timestamptz", "", True, "Created."),
        ("updated_at", "timestamptz", "", True, "Last update."),
    ]),
    ("realisasi.event_groups", "activity", 2, "Legacy grouping of one real event across units. Since Revisi V.1 each kegiatan has its own group.", [
        ("id", "uuid", "PK", False, "Row id."),
        ("created_by", "uuid", "LFK", True, "Creator."),
        ("created_at", "timestamptz", "", True, "Created."),
    ]),
    ("realisasi.academic_years", "calendar", 2, "Academic years. A start date outside every year cannot be submitted (R-09).", [
        ("id", "serial", "PK", False, "Row id."),
        ("label", "text", "UQ", False, "e.g. 2026/2027."),
        ("start_date", "date", "", False, "Year start."),
        ("end_date", "date", "", False, "Year end (> start)."),
    ]),
    ("realisasi.semesters", "calendar", 2, "Ganjil and Genap per academic year, with the freeze cutoff (R-55).", [
        ("id", "serial", "PK", False, "Row id."),
        ("academic_year_id", "int", "FK UQ", False, "Academic year (unique with term)."),
        ("term", "semester_term", "UQ", False, "ganjil | genap."),
        ("start_date", "date", "", False, "Semester start."),
        ("end_date", "date", "", False, "Semester end."),
        ("cutoff_date", "date", "", False, "Freeze date, ≥ end; default end + 30 days."),
    ]),
    ("realisasi.kpi_snapshots", "calendar", 2, "Frozen RENSTRA values at a semester cutoff. Never altered; re-freeze supersedes (R-56, R-58).", [
        ("id", "uuid", "PK", False, "Row id."),
        ("academic_year_id", "int", "FK", False, "Academic year."),
        ("kind", "snapshot_kind", "", False, "ganjil_ytd | genap_full_year."),
        ("window_start", "date", "", False, "Counting window start."),
        ("window_end", "date", "", False, "Counting window end."),
        ("cutoff_date", "date", "", False, "Cutoff used."),
        ("values", "jsonb", "", False, "Computed RENSTRA and Awards values."),
        ("settings_used", "jsonb", "", False, "Settings at freeze time (grace period etc.)."),
        ("frozen_at", "timestamptz", "", False, "Freeze time."),
        ("frozen_by", "uuid", "LFK", True, "IO Admin, or null for the scheduled job."),
        ("superseded_by", "uuid", "FK", True, "Newer snapshot after a re-freeze. One live snapshot per year and kind."),
        ("refreeze_reason", "text", "", True, "Mandatory reason on re-freeze."),
    ]),
    ("realisasi.kpi_snapshot_items", "calendar", 2, "Records behind each snapshot number, for drill-down and export.", [
        ("snapshot_id", "uuid", "PK FK", False, "Snapshot."),
        ("kpi_code", "text", "PK", False, "1.1, 1.19.S1, 1.19.24, awards…"),
        ("bucket", "text", "PK", False, "Split such as inbound/outbound, numerator/denominator."),
        ("ref_type", "text", "PK", False, "activity | student | chain …"),
        ("ref_id", "text", "PK", False, "Id of the contributing record."),
        ("is_late_addition", "boolean", "", False, "Verified after the previous freeze (Tambahan susulan, R-57)."),
    ]),

    # ------------------------------------------------------------------ participants
    ("realisasi.participant_set_versions", "participant", 3, "Versioned participant list of a kegiatan; only the approved version counts (R-21).", [
        ("id", "uuid", "PK", False, "Row id."),
        ("activity_id", "uuid", "FK UQ", False, "Kegiatan (unique with version)."),
        ("version", "int", "UQ", False, "1, 2, … per kegiatan."),
        ("status", "pset_status", "", False, "draft | pending | revision_requested | approved | superseded. At most one approved, one draft, one pending."),
        ("submitted_by", "uuid", "LFK", True, "Unit account or IO (post-verification edit)."),
        ("submitted_at", "timestamptz", "", True, "Submission time."),
        ("reviewed_by", "uuid", "LFK", True, "Mobility reviewer."),
        ("reviewed_at", "timestamptz", "", True, "Review time."),
        ("review_note", "text", "", True, "Revision note (required on revision, R-27)."),
    ]),
    ("realisasi.participant_students", "participant", 3, "PETRA (internal) and inbound students in a version. NRP must resolve in BAAK (R-16, R-17).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("set_version_id", "uuid", "FK UQ", False, "Participant version (unique with nrp, R-22)."),
        ("section", "student_section", "", False, "internal | inbound."),
        ("nrp", "text", "UQ LFK", False, "Student number; looked up in mock_baak.students."),
        ("full_name", "text", "", False, "From BAAK."),
        ("faculty_name", "text", "", True, "From BAAK."),
        ("prodi_name", "text", "", True, "From BAAK."),
        ("home_institution", "text", "", True, "Required for inbound."),
        ("home_student_number", "text", "", True, "Inbound home student number."),
        ("home_country_code", "text", "", True, "Inbound home country."),
    ]),
    ("realisasi.participant_staff", "participant", 3, "PETRA staff in a version. Recorded, not counted in RENSTRA 1.1 (R-19).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("set_version_id", "uuid", "FK UQ", False, "Participant version (unique with employee_id)."),
        ("employee_id", "text", "UQ LFK", False, "Employee id; looked up in mock_hr.employees."),
        ("full_name", "text", "", False, "From HR."),
        ("unit_name", "text", "", True, "From HR."),
    ]),
    ("realisasi.participant_conflicts", "participant", 3, "Same NRP claimed by two units' overlapping mobility kegiatan (rule 2.1, R-33). Mobility keeps one (R-34).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("nrp", "text", "UQ", False, "Student."),
        ("activity_a", "uuid", "FK UQ", False, "First kegiatan (a < b)."),
        ("activity_b", "uuid", "FK UQ", False, "Second kegiatan."),
        ("status", "conflict_status", "", False, "open | resolved. Open blocks approval (R-27a)."),
        ("kept_activity_id", "uuid", "FK", True, "Kegiatan that keeps the student; set iff resolved."),
        ("note", "text", "", True, "Decision note."),
        ("resolved_by", "uuid", "LFK", True, "Mobility member."),
        ("resolved_at", "timestamptz", "", True, "Decision time."),
        ("created_at", "timestamptz", "", True, "Detected."),
    ]),
    ("realisasi.activity_log", "participant", 3, "Update Log: verification, revision, edits with field diff (R-30, R-31).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("activity_id", "uuid", "FK", False, "Kegiatan."),
        ("kind", "log_kind", "", False, "verification | revision | update | system."),
        ("track", "team", "", True, "mobility, when the entry belongs to the track."),
        ("action", "text", "", False, "e.g. submit, approve, request_revision, edit."),
        ("actor_id", "uuid", "LFK", True, "Who did it."),
        ("note", "text", "", True, "Note."),
        ("diff", "jsonb", "", True, "Field-level diff."),
        ("in_frozen_period", "boolean", "", False, "Edit inside a frozen window (Perubahan Pasca-Beku)."),
        ("created_at", "timestamptz", "", True, "Time."),
    ]),

    # ------------------------------------------------------------------ ops + mocks
    ("realisasi.settings", "ops", 4, "Key/value settings edited by IO Admin. Snapshots copy what they used.", [
        ("key", "text", "PK", False, "grace_period_months, reporting_deadline_days, revision_reminder_days, deadline_reminder_before_days, demo_today."),
        ("value", "jsonb", "", False, "Value."),
        ("updated_by", "uuid", "LFK", True, "IO Admin."),
        ("updated_at", "timestamptz", "", True, "Last change."),
    ]),
    ("realisasi.team_members", "ops", 4, "IO team membership on top of the io_staff role.", [
        ("account_id", "uuid", "PK LFK", False, "Account."),
        ("team", "team", "PK", False, "mobility."),
    ]),
    ("mock_baak.students", "ops", 4, "Mock BAAK student registry used for NRP lookup.", [
        ("nrp", "text", "PK", False, "Student number."),
        ("full_name", "text", "", False, "Name."),
        ("faculty_code", "char(1)", "", False, "Faculty code."),
        ("faculty_name", "text", "", False, "Faculty."),
        ("prodi_name", "text", "", False, "Study programme."),
        ("category", "text", "", False, "regular | inbound_exchange (inbound must be inbound_exchange)."),
        ("home_institution", "text", "", True, "Inbound home institution."),
        ("home_country_code", "text", "", True, "Inbound home country."),
        ("intake_year", "int", "", False, "Angkatan."),
        ("status", "text", "", False, "active | graduated | inactive (warning, not block, R-18)."),
    ]),
    ("mock_hr.employees", "ops", 4, "Mock HR registry used for employee-id lookup.", [
        ("employee_id", "text", "PK", False, "Employee id (NIP)."),
        ("full_name", "text", "", False, "Name."),
        ("unit_name", "text", "", False, "Unit."),
        ("position", "text", "", True, "Position."),
        ("status", "text", "", False, "active | inactive."),
    ]),
    ("realisasi.notifications", "ops", 4, "In-app notifications.", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("recipient_id", "uuid", "LFK", False, "Recipient account."),
        ("kind", "text", "", False, "Event kind (revision_requested, verified, reminder…)."),
        ("title", "text", "", False, "Title."),
        ("body", "text", "", True, "Body."),
        ("link", "text", "", True, "Target page."),
        ("read_at", "timestamptz", "", True, "Read time."),
        ("created_at", "timestamptz", "", True, "Created."),
    ]),
    ("realisasi.email_outbox", "ops", 4, "Emails queued (logged, not sent, in the mockup).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("to_email", "text", "", False, "Recipient."),
        ("subject", "text", "", False, "Subject."),
        ("body", "text", "", False, "Body."),
        ("created_at", "timestamptz", "", True, "Queued."),
        ("sent_at", "timestamptz", "", True, "Sent."),
    ]),
    ("realisasi.export_log", "ops", 4, "Every Excel export, especially those with personal data (R-63).", [
        ("id", "bigserial", "PK", False, "Row id."),
        ("actor_id", "uuid", "LFK", True, "Who exported."),
        ("export_kind", "text", "", False, "Report type."),
        ("filters", "jsonb", "", True, "Filters incl. period."),
        ("row_count", "int", "", True, "Rows exported."),
        ("contains_personal_data", "boolean", "", False, "Participant data included."),
        ("created_at", "timestamptz", "", True, "Time."),
    ]),
    ("realisasi.file_blobs", "ops", 4, "Storage emulation for uploaded files (local/mock deployments).", [
        ("path", "text", "PK", False, "bucket/…; referenced by activity_files.storage_path."),
        ("bucket", "text", "", False, "realisasi-files | realisasi-transcripts."),
        ("data", "bytea", "", False, "File content."),
        ("mime", "text", "", False, "MIME type."),
        ("size_bytes", "int", "", False, "≤ 10 485 760."),
        ("created_by", "uuid", "LFK", True, "Uploader."),
        ("created_at", "timestamptz", "", False, "Upload time."),
    ]),
    ("realisasi.deployment_flags", "ops", 4, "DBA-only switches, e.g. demo_time_travel.", [
        ("key", "text", "PK", False, "Flag name."),
        ("enabled", "boolean", "", False, "On/off."),
    ]),
    ("realisasi.job_marks", "ops", 4, "Idempotency marks for scheduled jobs (reminders, freezes).", [
        ("key", "text", "PK", False, "Job + period key."),
        ("created_at", "timestamptz", "", False, "When it ran."),
    ]),
]

# (child table, child column, parent table, parent column, kind) kind: "fk" solid, "lfk" dashed (logical)
RELS = [
    ("kerjasama.document_partners", "document_id", "kerjasama.documents", "id", "lfk"),
    ("kerjasama.document_partners", "partner_id", "kerjasama.partners", "id", "lfk"),
    ("kerjasama.document_scope_units", "unit_id", "kerjasama.units", "id", "lfk"),
    ("kerjasama.partners", "country_code", "kerjasama.countries", "code", "lfk"),
    ("realisasi.account_roles", "akun_id", "kerjasama.profiles", "akun_id", "lfk"),
    ("realisasi.activity_units", "unit_id", "kerjasama.units", "id", "lfk"),
    ("realisasi.agenda_rules", "agenda_id", "kerjasama.agendas", "id", "lfk"),
    ("realisasi.activity_documents", "original_document_id", "kerjasama.documents", "id", "lfk"),
    ("realisasi.document_overrides", "document_id", "kerjasama.documents", "id", "lfk"),
    ("realisasi.activity_partner_snapshot", "partner_id", "kerjasama.partners", "id", "lfk"),
    ("realisasi.activity_external_persons", "country_code", "kerjasama.countries", "code", "lfk"),
    ("realisasi.activity_sdgs", "sdg_id", "realisasi.sdgs", "id", "fk"),
    ("realisasi.activity_units", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_documents", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_partner_snapshot", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_sdgs", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_external_persons", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_files", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.activities", "agenda_id", "realisasi.agenda_rules", "agenda_id", "lfk"),
    ("realisasi.activities", "event_group_id", "realisasi.event_groups", "id", "fk"),
    ("realisasi.activities", "academic_year_id", "realisasi.academic_years", "id", "fk"),
    ("realisasi.activities", "semester_id", "realisasi.semesters", "id", "fk"),
    ("realisasi.semesters", "academic_year_id", "realisasi.academic_years", "id", "fk"),
    ("realisasi.kpi_snapshots", "academic_year_id", "realisasi.academic_years", "id", "fk"),
    ("realisasi.kpi_snapshot_items", "snapshot_id", "realisasi.kpi_snapshots", "id", "fk"),
    ("realisasi.participant_set_versions", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.participant_conflicts", "activity_a", "realisasi.activities", "id", "fk"),
    ("realisasi.activity_log", "activity_id", "realisasi.activities", "id", "fk"),
    ("realisasi.participant_students", "set_version_id", "realisasi.participant_set_versions", "id", "fk"),
    ("realisasi.participant_staff", "set_version_id", "realisasi.participant_set_versions", "id", "fk"),
    ("realisasi.participant_students", "nrp", "mock_baak.students", "nrp", "lfk"),
    ("realisasi.participant_staff", "employee_id", "mock_hr.employees", "employee_id", "lfk"),
]

ENUMS = [
    ("activity_status", "draft, in_verification, revision_requested, verified", "Overall kegiatan status, derived from the mobility track (R-25)."),
    ("track_status", "not_required, pending, revision_requested, approved", "Mobility verification track (R-23)."),
    ("direction", "inbound, outbound", "Per kegiatan (R-07b)."),
    ("mobility_category", "jd_dd, student_exchange, short_summer, other_mobility", "Award column for mobility agendas (R-49)."),
    ("activity_mode", "offline, online, hybrid", "Moda."),
    ("file_kind", "ia, ir, mobility_bundle, evidence", "Uploaded file type."),
    ("person_role", "speaker, visiting_lecturer, researcher, staff_visitor, other", "External person role."),
    ("student_section", "internal, inbound", "PETRA vs inbound student."),
    ("pset_status", "draft, pending, revision_requested, approved, superseded", "Participant version status."),
    ("semester_term", "ganjil, genap", "Semester."),
    ("snapshot_kind", "ganjil_ytd, genap_full_year", "Snapshot type (Ganjil = YTD, Genap = Setahun)."),
    ("conflict_status", "open, resolved", "Duplicate-student conflict."),
    ("log_kind", "verification, revision, update, system", "Update Log entry type."),
    ("team", "mobility", "IO team (only Mobility since Revisi V.1)."),
]

VIEWS = [
    ("realisasi.v_chains", "Renewal chains: every document with its chain root, used for RENSTRA 1.19.24 (R-42)."),
    ("realisasi.v_activity_documents", "Activity → original and current document through the chain (R-03)."),
    ("realisasi.v_activity_list", "Flattened activity list behind every list screen and the Excel export."),
]
