-- seed-supabase/06_kegiatan_2025_2026_d (simks-partnership): GENERATED by scripts/gen-supabase-bulk-seed.py; do not edit by hand.
-- AY 2025/2026 step 4/5: kegiatan 161-180 (all by Program Studi), with peserta.
-- Self-contained and idempotent (existing rows are skipped), so it can be run on its own: Supabase SQL Editor or one
-- statement batch. Writes only realisasi.* and mock_baak/mock_hr; SIM Kerjasama tables are only read.

create or replace function pg_temp.aid(n int) returns uuid language sql immutable as $$
  select ('b5000000-0000-4000-8000-' || lpad(n::text, 12, '0'))::uuid $$;
create or replace function pg_temp.gid(n int) returns uuid language sql immutable as $$
  select ('e5000000-0000-4000-8000-' || lpad(n::text, 12, '0'))::uuid $$;
create or replace function pg_temp.akun(p_akun int) returns uuid language sql stable as $$
  select id from kerjasama.profiles where akun_id = p_akun $$;
create or replace function pg_temp.pdf() returns bytea language sql immutable as $$
  select decode('255044462d312e340a312030206f626a0a3c3c2f547970652f436174616c6f672f50616765732032203020523e3e0a656e646f626a0a322030206f626a0a3c3c2f547970652f50616765732f4b6964735b33203020525d2f436f756e7420313e3e0a656e646f626a0a332030206f626a0a3c3c2f547970652f506167652f506172656e742032203020522f4d65646961426f785b30203020323030203230305d2f436f6e74656e74732034203020522f5265736f75726365733c3c3e3e3e3e0a656e646f626a0a342030206f626a0a3c3c2f4c656e67746820303e3e73747265616d0a0a656e6473747265616d0a656e646f626a0a787265660a3020350a303030303030303030302036353533352066200a30303030303030303039203030303030206e200a30303030303030303534203030303030206e200a30303030303030313035203030303030206e200a30303030303030313939203030303030206e200a747261696c65720a3c3c2f53697a6520352f526f6f742031203020523e3e0a7374617274787265660a3234350a2525454f460a', 'hex') $$;
create or replace function pg_temp.wib(d date, t time default '09:00') returns timestamptz language sql immutable as $$
  select (d + t) at time zone 'Asia/Jakarta' $$;

-- preconditions: accounts seeded (03_accounts.sql) and the bulk registries present (05_registries_bulk.sql)
do $$
begin
  if pg_temp.akun(1) is null or pg_temp.akun(4) is null or pg_temp.akun(10) is null or pg_temp.akun(11) is null then
    raise exception 'run seed-supabase/03_accounts.sql first (account_roles for akun 1, 4, 10, 11)';
  end if;
  if not exists (select 1 from mock_baak.students where nrp like '%6___' and length(nrp) = 9 and nrp ~ '^[A-H]\d{4}[6-8]\d{3}$') then
    raise exception 'run seed-supabase/05_registries_bulk.sql first';
  end if;
end $$;

-- one kegiatan with its units, kerja sama, SDGs, external persons, files and log (skipped when it exists).
-- Creator: the Prodi Manajemen submitter (akun 4) for unit 5, otherwise IO Admin (akun 1) on behalf of the prodi.
create or replace function pg_temp.keg(
  p_n int, p_name text, p_unit int, p_agenda int, p_dir text, p_start date, p_end date, p_mode text, p_venue text,
  p_country text, p_doc int, p_sdgs int[], p_submitted timestamptz, p_mstatus text, p_msince timestamptz,
  p_files text[], p_mnote text, p_ext jsonb)
returns void language plpgsql as $f$
declare v_id uuid := pg_temp.aid(p_n); v_g uuid := pg_temp.gid(p_n);
        v_creator uuid := pg_temp.akun(case when p_unit = 5 then 4 else 1 end);
        v_mobt uuid := pg_temp.akun(case when p_n % 2 = 0 then 10 else 11 end);
        v_mob boolean := realisasi.agenda_is_mobility(p_agenda);
        v_created timestamptz; v_code text; k text; v_path text; e jsonb;
begin
  if exists (select 1 from realisasi.activities where id = v_id) then return; end if;
  if not exists (select 1 from kerjasama.units where id = p_unit and kind = 'prodi') then
    raise exception 'kegiatan %: unit % is not a Program Studi', p_n, p_unit;
  end if;
  if not exists (select 1 from kerjasama.agendas where id = p_agenda) then raise exception 'kegiatan %: agenda % missing', p_n, p_agenda; end if;
  if not exists (select 1 from realisasi.documents_valid_between(p_start, p_end) v where v.document_id = p_doc) then
    raise exception 'kegiatan %: document % not valid for % - %', p_n, p_doc, p_start, p_end;
  end if;
  v_created := coalesce(p_submitted - interval '2 days', pg_temp.wib(least(p_end, realisasi.today()) - 1));
  v_code := 'RL-' || to_char(v_created at time zone 'Asia/Jakarta', 'YYYY') || '-' || lpad(p_n::text, 4, '0');
  insert into realisasi.event_groups (id, created_by, created_at) values (v_g, v_creator, v_created) on conflict do nothing;
  insert into realisasi.activities (id, code, name, agenda_id, direction, start_date, end_date, mode, venue, country_code,
              sks_recognized, description, submitter_unit_id, created_by, submitted_at, verified_at,
              mobility_status, mobility_since, event_group_id, created_at, updated_at)
  values (v_id, v_code, p_name, p_agenda, p_dir::realisasi.direction, p_start, p_end, p_mode::realisasi.activity_mode, p_venue,
          p_country, case when v_mob and p_dir = 'outbound' then case when p_end - p_start >= 80 then 20 when p_end - p_start >= 20 then 6 else 2 end end,
          'Kegiatan "' || p_name || '" sebagai implementasi kerja sama dengan mitra.', p_unit, v_creator, p_submitted,
          case when p_submitted is not null and (not v_mob or p_mstatus = 'approved')
               then coalesce(case when v_mob then p_msince end, p_submitted) end,
          case when p_submitted is null or not v_mob then 'not_required' else p_mstatus end::realisasi.track_status,
          coalesce(p_msince, p_submitted, v_created), v_g, v_created, coalesce(p_msince, p_submitted, v_created));
  insert into realisasi.activity_units (activity_id, unit_id, is_submitter) values (v_id, p_unit, true);
  insert into realisasi.activity_documents (activity_id, original_document_id, out_of_scope_warning)
  values (v_id, p_doc, not exists (select 1 from kerjasama.document_scope_units su where su.document_id = p_doc and su.unit_id = p_unit));
  insert into realisasi.activity_sdgs (activity_id, sdg_id) select v_id, s from unnest(p_sdgs) s;
  for e in select * from jsonb_array_elements(p_ext) loop
    insert into realisasi.activity_external_persons (activity_id, full_name, institution, country_code, role, notes)
    values (v_id, e ->> 'full_name', e ->> 'institution', e ->> 'country_code', (e ->> 'role')::realisasi.person_role, e ->> 'notes');
  end loop;
  foreach k in array p_files || case when v_mob and p_submitted is not null then '{mobility_bundle}'::text[] else '{}' end loop
    v_path := case when k = 'mobility_bundle' then 'realisasi-transcripts/' else 'realisasi-files/' end
              || v_id || '/' || k || '/' || md5(v_id::text || k)::uuid || '.pdf';
    insert into realisasi.file_blobs (path, bucket, data, mime, size_bytes, created_by, created_at)
    values (v_path, split_part(v_path, '/', 1), pg_temp.pdf(), 'application/pdf', length(pg_temp.pdf()), v_creator, v_created + interval '1 hour')
    on conflict (path) do nothing;
    insert into realisasi.activity_files (activity_id, kind, version, storage_path, filename, size_bytes, mime, is_current, uploaded_by, uploaded_at)
    values (v_id, k::realisasi.file_kind, 1, v_path,
            case when k = 'mobility_bundle' then 'Transkrip_Poster_Dokumentasi_' else upper(k) || '_' end || v_code || '.pdf',
            length(pg_temp.pdf()), 'application/pdf', true, v_creator, v_created + interval '1 hour');
  end loop;

  insert into realisasi.activity_log (activity_id, kind, track, action, actor_id, note, diff, in_frozen_period, created_at)
  values (v_id, 'system', null, 'create', v_creator, null, null, false, v_created);
  if p_submitted is null then return; end if;
  insert into realisasi.activity_log (activity_id, kind, track, action, actor_id, note, diff, in_frozen_period, created_at)
  values (v_id, 'system', null, 'submit', v_creator, null, null, false, p_submitted);
  if v_mob and p_mstatus = 'approved' then
    insert into realisasi.activity_log (activity_id, kind, track, action, actor_id, note, diff, in_frozen_period, created_at)
    values (v_id, 'verification', 'mobility', 'approve', v_mobt, null, '{"version":1}', false, p_msince);
  elsif v_mob and p_mstatus = 'revision_requested' then
    insert into realisasi.activity_log (activity_id, kind, track, action, actor_id, note, diff, in_frozen_period, created_at)
    values (v_id, 'verification', 'mobility', 'request_revision', v_mobt, p_mnote, null, false, p_msince);
  end if;
end $f$;

-- participant set v1: PETRA students (internal), inbound students and internal staff from the mock registries
create or replace function pg_temp.peserta(p_n int, p_status text, p_internal text[], p_inbound text[], p_staff text[],
  p_submitted timestamptz, p_reviewed timestamptz) returns void language plpgsql as $f$
declare v_act uuid := pg_temp.aid(p_n); v_id uuid := md5(pg_temp.aid(p_n)::text || ':v1')::uuid; v_by uuid;
begin
  if exists (select 1 from realisasi.participant_set_versions where id = v_id) then return; end if;
  select created_by into v_by from realisasi.activities where id = v_act;
  insert into realisasi.participant_set_versions (id, activity_id, version, status, submitted_by, submitted_at, reviewed_by, reviewed_at)
  values (v_id, v_act, 1, p_status::realisasi.pset_status, case when p_submitted is not null then v_by end, p_submitted,
          case when p_reviewed is not null then pg_temp.akun(case when p_n % 2 = 0 then 10 else 11 end) end, p_reviewed);
  insert into realisasi.participant_students (set_version_id, section, nrp, full_name, faculty_name, prodi_name)
  select v_id, 'internal', s.nrp, s.full_name, s.faculty_name, s.prodi_name
    from unnest(p_internal) with ordinality x(nrp, o) join mock_baak.students s on s.nrp = x.nrp order by o;
  insert into realisasi.participant_students (set_version_id, section, nrp, full_name, faculty_name, prodi_name,
              home_institution, home_student_number, home_country_code)
  select v_id, 'inbound', s.nrp, s.full_name, s.faculty_name, s.prodi_name, s.home_institution, 'HS-' || right(s.nrp, 5), s.home_country_code
    from unnest(p_inbound) with ordinality x(nrp, o) join mock_baak.students s on s.nrp = x.nrp order by o;
  insert into realisasi.participant_staff (set_version_id, employee_id, full_name, unit_name)
  select v_id, e.employee_id, e.full_name, e.unit_name
    from unnest(p_staff) with ordinality x(id, o) join mock_hr.employees e on e.employee_id = x.id order by o;
  if (select count(*) from realisasi.participant_students where set_version_id = v_id)
     <> coalesce(cardinality(p_internal), 0) + coalesce(cardinality(p_inbound), 0) then
    raise exception 'kegiatan %: a student NRP is missing from mock_baak.students', p_n;
  end if;
end $f$;

-- 161: Program Studi Teknik Mesin
select pg_temp.keg(161, 'Studi Ekskursi Teknik Mesin ke Kyoto Sangyo University, Kyoto', 69, 24, 'outbound', '2026-05-31', '2026-06-03', 'offline', 'Kyoto Sangyo University, Kyoto', 'JP', 11, '{4,12}', pg_temp.wib('2026-06-23', '16:00'), 'approved', pg_temp.wib('2026-07-10', '12:00'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(161, 'approved', '{B14256589,B14248838,B14238223,B14236733,B14256141,B14257666,B14258081,B14237695,B14248236,B14238838}', '{}', '{PG603179}', pg_temp.wib('2026-06-23', '16:00'), pg_temp.wib('2026-07-10', '12:00'));

-- 162: Program Studi Teknik Mesin
select pg_temp.keg(162, 'Magang Internasional Teknik Mesin di University of Amsterdam', 69, 21, 'outbound', '2026-03-02', '2026-04-12', 'offline', 'University of Amsterdam', 'NL', 17, '{7}', pg_temp.wib('2026-04-28', '11:30'), 'approved', pg_temp.wib('2026-05-14', '13:30'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(162, 'approved', '{B14256141,B14237695,B14248258,B14257666}', '{}', '{PG603179}', pg_temp.wib('2026-04-28', '11:30'), pg_temp.wib('2026-05-14', '13:30'));

-- 163: Prodi Kedokteran
select pg_temp.keg(163, 'Magang Internasional Kedokteran di University of Amsterdam', 76, 21, 'outbound', '2026-03-30', '2026-05-12', 'offline', 'University of Amsterdam', 'NL', 17, '{4,6,17}', pg_temp.wib('2026-06-02', '14:15'), 'approved', pg_temp.wib('2026-06-13', '16:30'), '{ia,ir}', null, '[{"full_name": "Prof. Pieter van Dijk", "institution": "University of Amsterdam", "country_code": "NL", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(163, 'approved', '{G61257371,G61228465}', '{}', '{}', pg_temp.wib('2026-06-02', '14:15'), pg_temp.wib('2026-06-13', '16:30'));

-- 164: Prodi Manajemen
select pg_temp.keg(164, 'Studi Ekskursi Manajemen ke Yogyakarta', 5, 24, 'outbound', '2026-06-07', '2026-06-09', 'offline', 'Yogyakarta', 'ID', 12, '{4,9,17}', pg_temp.wib('2026-06-19', '16:00'), 'approved', pg_temp.wib('2026-07-07', '14:00'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(164, 'approved', '{D31237873,D31248101,D31256312,D31237888,D31247028,D31236101,D31228283,D31248402,D31258883,D31227308}', '{}', '{PG661938}', pg_temp.wib('2026-06-19', '16:00'), pg_temp.wib('2026-07-07', '14:00'));

-- 165: Program Studi Desain Komunikasi Visual
select pg_temp.keg(165, 'MBKM Pertukaran Mahasiswa Desain Komunikasi Visual di PT Unilever Indonesia Tbk', 63, 38, 'outbound', '2026-03-02', '2026-06-15', 'offline', 'PT Unilever Indonesia Tbk', 'ID', 21, '{4,11,12}', pg_temp.wib('2026-08-06', '12:45'), 'approved', pg_temp.wib('2026-08-15', '10:00'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(165, 'approved', '{C21236671,C21247016,C21236260}', '{}', '{PG526649,PG657693}', pg_temp.wib('2026-08-06', '12:45'), pg_temp.wib('2026-08-15', '10:00'));

-- 166: Program Studi Magister Teknik Sipil
select pg_temp.keg(166, 'Magang Industri Magister Teknik Sipil di PT Astra International Tbk', 56, 21, 'outbound', '2026-04-20', '2026-05-31', 'offline', 'PT Astra International Tbk', 'ID', 23, '{11}', pg_temp.wib('2026-06-15', '10:30'), 'approved', pg_temp.wib('2026-06-30', '15:30'), '{ia,ir}', null, '[{"full_name": "Hendro Saputro, S.E., M.M.", "institution": "PT Astra International Tbk", "country_code": "ID", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(166, 'approved', '{A14248811,A14246094,A14247655,A14257290,A14248809,A14248433}', '{}', '{}', pg_temp.wib('2026-06-15', '10:30'), pg_temp.wib('2026-06-30', '15:30'));

-- 167: Prodi Akuntansi
select pg_temp.keg(167, 'Magang Industri Akuntansi di PT Unilever Indonesia Tbk', 6, 21, 'outbound', '2026-04-13', '2026-06-03', 'offline', 'PT Unilever Indonesia Tbk', 'ID', 21, '{16}', pg_temp.wib('2026-06-17', '09:30'), 'approved', pg_temp.wib('2026-07-05', '12:30'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(167, 'approved', '{D32227188,D32248005,D32227795,D32257463,D32237743}', '{}', '{PG641614}', pg_temp.wib('2026-06-17', '09:30'), pg_temp.wib('2026-07-05', '12:30'));

-- 168: Program Studi Bahasa Mandarin
select pg_temp.keg(168, 'Studi Ekskursi Bahasa Mandarin ke Bandung', 58, 24, 'outbound', '2026-05-21', '2026-05-24', 'offline', 'Bandung', 'ID', 28, '{4,17}', pg_temp.wib('2026-06-03', '12:15'), 'approved', pg_temp.wib('2026-06-16', '12:00'), '{ia,ir}', null, '[{"full_name": "Prof. Bambang Wicaksono", "institution": "Universitas Gadjah Mada", "country_code": "ID", "role": "other", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(168, 'approved', '{E43237395,E43236934,E43257300,E43248713,E43228663,E43238216,E43258937,E43246366,E43237289,E43247625}', '{}', '{PG616473,PG663932}', pg_temp.wib('2026-06-03', '12:15'), pg_temp.wib('2026-06-16', '12:00'));

-- 169: Program Studi Teknik Elektro
select pg_temp.keg(169, 'Magang Industri Teknik Elektro di PT Astra International Tbk', 65, 21, 'outbound', '2026-06-01', '2026-06-30', 'offline', 'PT Astra International Tbk', 'ID', 23, '{9,17}', pg_temp.wib('2026-07-09', '14:30'), 'approved', pg_temp.wib('2026-07-16', '16:00'), '{ia,ir}', null, '[]'::jsonb);
select pg_temp.peserta(169, 'approved', '{B12237202,B12236482,B12247079,B12248934,B12247442}', '{}', '{PG616609,PG578721}', pg_temp.wib('2026-07-09', '14:30'), pg_temp.wib('2026-07-16', '16:00'));

-- 170: Program Studi Bahasa Mandarin
select pg_temp.keg(170, 'Short Program (Inbound) Kyoto Sangyo – Linguistik Terapan', 58, 23, 'inbound', '2026-05-18', '2026-05-29', 'offline', 'Kampus PCU Siwalankerto', 'ID', 11, '{4,10}', pg_temp.wib('2026-06-11', '15:30'), 'approved', pg_temp.wib('2026-06-24', '13:00'), '{ia,ir}', null, '[{"full_name": "Dr. Emi Fujita", "institution": "Kyoto Sangyo University", "country_code": "JP", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(170, 'approved', '{}', '{X04260308,X04260310,X04260312,X04260304}', '{PG663932,PG616473}', pg_temp.wib('2026-06-11', '15:30'), pg_temp.wib('2026-06-24', '13:00'));

-- 171: Prodi Kedokteran
select pg_temp.keg(171, 'Cultural Exchange (Inbound) NTU – Telemedisin', 76, 29, 'inbound', '2026-03-23', '2026-03-30', 'offline', 'Gedung Q PCU', 'ID', 15, '{4}', pg_temp.wib('2026-04-06', '09:30'), 'approved', pg_temp.wib('2026-04-17', '14:30'), '{ia,ir}', null, '[{"full_name": "Dr. Lin Chia-Hao", "institution": "National Taiwan University", "country_code": "TW", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(171, 'approved', '{}', '{X03250313,X04260316,X04260320,X03250317}', '{PG615813,PG505398}', pg_temp.wib('2026-04-06', '09:30'), pg_temp.wib('2026-04-17', '14:30'));

-- 172: Program Studi Arsitektur
select pg_temp.keg(172, 'Cultural Exchange (Inbound) Kyoto Sangyo – Desain Kota Pesisir', 54, 29, 'inbound', '2026-02-02', '2026-02-10', 'offline', 'Gedung P PCU', 'ID', 11, '{4,11,13}', pg_temp.wib('2026-02-14', '10:30'), 'approved', pg_temp.wib('2026-02-19', '14:30'), '{ia,ir}', null, '[{"full_name": "Dr. Hiroshi Kato", "institution": "Kyoto Sangyo University", "country_code": "JP", "role": "other", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(172, 'approved', '{}', '{X03250303,X03250307,X04260310,X04260306,X03250309}', '{PG635480,PG539055}', pg_temp.wib('2026-02-14', '10:30'), pg_temp.wib('2026-02-19', '14:30'));

-- 173: Prodi Manajemen
select pg_temp.keg(173, 'Academic Exchange (Inbound) Chulalongkorn – Manajemen Rantai Pasok', 5, 28, 'inbound', '2026-02-23', '2026-06-03', 'offline', 'Gedung P PCU', 'ID', 29, '{4,12}', pg_temp.wib('2026-06-23', '14:30'), 'approved', pg_temp.wib('2026-07-08', '16:00'), '{ia,ir}', null, '[{"full_name": "Asst. Prof. Kanokwan Srisuk", "institution": "Chulalongkorn University", "country_code": "TH", "role": "other", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(173, 'approved', '{}', '{X04260344,X04260346,X04260342}', '{}', pg_temp.wib('2026-06-23', '14:30'), pg_temp.wib('2026-07-08', '16:00'));

-- 174: Program Studi Desain Interior
select pg_temp.keg(174, 'Cultural Exchange (Inbound) NTU – Ilustrasi dan Narasi Visual', 59, 29, 'inbound', '2026-05-11', '2026-05-18', 'offline', 'Gedung P PCU', 'ID', 15, '{4,9,12}', pg_temp.wib('2026-06-02', '12:00'), 'approved', pg_temp.wib('2026-06-20', '10:00'), '{ia,ir}', null, '[{"full_name": "Dr. Lin Chia-Hao", "institution": "National Taiwan University", "country_code": "TW", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(174, 'approved', '{}', '{X04260314,X03250319,X03250315,X04260318,X04260322}', '{PG600979}', pg_temp.wib('2026-06-02', '12:00'), pg_temp.wib('2026-06-20', '10:00'));

-- 175: Program Studi Teknik Elektro
select pg_temp.keg(175, 'Cultural Exchange (Inbound) Yonsei – Elektronika Daya', 65, 29, 'inbound', '2026-05-25', '2026-05-29', 'offline', 'Gedung Q PCU', 'ID', 31, '{4,7,13}', pg_temp.wib('2026-06-08', '09:00'), 'approved', pg_temp.wib('2026-06-18', '11:30'), '{ia,ir}', null, '[{"full_name": "Prof. Park Jae-hyun", "institution": "Yonsei University", "country_code": "KR", "role": "other", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(175, 'approved', '{}', '{X03250355,X04260356,X03250353,X04260352,X03250357}', '{PG546039,PG578721}', pg_temp.wib('2026-06-08', '09:00'), pg_temp.wib('2026-06-18', '11:30'));

-- 176: Prodi Manajemen
select pg_temp.keg(176, 'Cultural Exchange (Inbound) Chulalongkorn – Kewirausahaan Digital', 5, 29, 'inbound', '2026-05-18', '2026-05-25', 'offline', 'Gedung Q PCU', 'ID', 25, '{4,9,17}', pg_temp.wib('2026-07-19', '10:00'), 'approved', pg_temp.wib('2026-07-25', '16:30'), '{ia,ir}', null, '[{"full_name": "Asst. Prof. Kanokwan Srisuk", "institution": "Chulalongkorn University", "country_code": "TH", "role": "other", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(176, 'approved', '{}', '{X03250347,X04260348,X03250343}', '{PG643269,PG661938}', pg_temp.wib('2026-07-19', '10:00'), pg_temp.wib('2026-07-25', '16:30'));

-- 177: Program Studi Teknik Sipil
select pg_temp.keg(177, 'Academic Exchange (Inbound) Kyoto Sangyo – Manajemen Konstruksi', 55, 28, 'inbound', '2026-03-16', '2026-06-14', 'offline', 'Ruang Seminar Gedung W PCU', 'ID', 11, '{6,11}', pg_temp.wib('2026-06-27', '11:00'), 'approved', pg_temp.wib('2026-07-08', '14:00'), '{ia,ir}', null, '[{"full_name": "Prof. Kenji Watanabe", "institution": "Kyoto Sangyo University", "country_code": "JP", "role": "staff_visitor", "notes": "Koordinator program dari mitra"}]'::jsonb);
select pg_temp.peserta(177, 'approved', '{}', '{X03250311,X04260306,X03250301,X03250307}', '{}', pg_temp.wib('2026-06-27', '11:00'), pg_temp.wib('2026-07-08', '14:00'));

-- 178: Prodi Manajemen
select pg_temp.keg(178, 'Seminar Internasional Manajemen Rantai Pasok bersama UGM', 5, 10, 'inbound', '2026-02-10', '2026-02-10', 'online', 'Zoom Meeting', null, 28, '{8,12}', pg_temp.wib('2026-02-19', '14:45'), null, null, '{ia,ir}', null, '[{"full_name": "Hendro Saputro, S.E., M.M.", "institution": "Universitas Gadjah Mada", "country_code": "ID", "role": "speaker"}, {"full_name": "Dra. Sri Wahyuni, M.Si.", "institution": "Universitas Gadjah Mada", "country_code": "ID", "role": "speaker"}]'::jsonb);

-- 179: Program Studi Desain Interior
select pg_temp.keg(179, 'Staff Exchange Dosen Desain Interior ke PT Unilever Indonesia Tbk', 59, 3, 'outbound', '2026-06-01', '2026-06-13', 'hybrid', 'PT Unilever Indonesia Tbk', 'ID', 21, '{4,12}', pg_temp.wib('2026-07-24', '09:45'), null, null, '{ia,ir}', null, '[{"full_name": "Dra. Sri Wahyuni, M.Si.", "institution": "PT Unilever Indonesia Tbk", "country_code": "ID", "role": "staff_visitor"}, {"full_name": "Prof. Bambang Wicaksono", "institution": "PT Unilever Indonesia Tbk", "country_code": "ID", "role": "other"}]'::jsonb);

-- 180: Program Studi Magister Arsitektur
select pg_temp.keg(180, 'Seminar Internasional Arsitektur Tropis bersama Astra', 53, 10, 'inbound', '2026-05-26', '2026-05-26', 'offline', 'Kampus PCU Siwalankerto', 'ID', 23, '{4,13}', pg_temp.wib('2026-06-14', '08:15'), null, null, '{ia,ir}', null, '[{"full_name": "Prof. Bambang Wicaksono", "institution": "PT Astra International Tbk", "country_code": "ID", "role": "speaker"}]'::jsonb);
