-- seed-supabase/08_refreeze_2025_2026 (simks-partnership): GENERATED by scripts/gen-supabase-bulk-seed.py; do not edit by hand.
-- Re-freezes the AY 2025/2026 snapshots once after the bulk import (R-58), as of their original freeze moments, so
-- Ganjil and Setahun include the imported kegiatan; the earlier snapshots stay as superseded. No-op on a fresh install
-- (90_freeze.sql freezes later) and when already done.
-- Self-contained and idempotent (existing rows are skipped), so it can be run on its own: Supabase SQL Editor or one
-- statement batch. Writes only realisasi.* and mock_baak/mock_hr; SIM Kerjasama tables are only read.

do $$
declare s realisasi.kpi_snapshots; v_reason text := 'Bekukan ulang setelah impor data kegiatan 2025/2026';
begin
  for s in select * from realisasi.kpi_snapshots
            where academic_year_id = 1 and superseded_by is null and refreeze_reason is distinct from v_reason
              and exists (select 1 from realisasi.activities a where a.id = ('b5000000-0000-4000-8000-' || lpad('101', 12, '0'))::uuid)
            order by frozen_at
  loop
    perform realisasi._freeze(s.academic_year_id, s.kind, s.frozen_at, (select id from kerjasama.profiles where akun_id = 1),
                              v_reason, s.id);
  end loop;
end $$;
