-- seed-supabase/09_registries_tambahan (simks-partnership): mock BAAK students for the additional bulk kegiatan
-- (10_kegiatan_tambahan_1..8 = kegiatan 221-420). Each 10_kegiatan_tambahan_N file owns one disjoint slice (marked
-- below), so the new kegiatan never share a student with each other or with the 06/07 kegiatan (no new conflicts).
-- NRPs use sequence digit 9 ({prefix}{intake}9{nnn}); inbound X05/X06. Prodi/faculty names follow 05_registries_bulk.
-- Self-contained and idempotent (existing rows are skipped). Writes only mock_baak; SIM Kerjasama tables are only read.
insert into mock_baak.students (nrp, full_name, faculty_code, faculty_name, prodi_name, category, home_institution, home_country_code, intake_year, status) values
  -- 10_kegiatan_tambahan_1
  ('B11239558', 'Fiona Chandra', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11239097', 'Samuel Hadinata', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11229093', 'Bryan Suryadi', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11239548', 'Fiona Rusli', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11249656', 'Kevin Prawira', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B11259876', 'Joshua Hartanto', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2025, 'active'),
  ('B11229911', 'Carissa Wibisono', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11249376', 'Felix Lim', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B11239054', 'Michelle Kartika', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11239992', 'Evan Lim', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11249731', 'Michelle Hadinata', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B11259793', 'Nicholas Hartanto', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2025, 'active'),
  ('B11229772', 'Aurelia Susilo', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11249484', 'Tiffany Tanuwijaya', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B13249805', 'Sharon Tan', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2024, 'active'),
  ('B13239251', 'Evan Halim', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2023, 'active'),
  ('B13249021', 'Valencia Santoso', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2024, 'active'),
  ('B13249069', 'Alvin Soetomo', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2024, 'active'),
  ('B13259437', 'Owen Halim', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2025, 'active'),
  ('B13259187', 'Stefanie Pangestu', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2025, 'active'),
  ('B13249780', 'Ricky Halim', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2024, 'active'),
  ('B13239748', 'Adrian Widjaja', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2023, 'active'),
  ('B13249311', 'Glory Prawira', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2024, 'active'),
  ('B13239273', 'Aurelia Lim', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2023, 'active'),
  ('B13239019', 'Agnes Pangestu', 'B', 'Fakultas Teknologi Industri', 'Teknik Industri', 'regular', null, null, 2023, 'active'),
  ('X06269001', 'Yu-ting Hsieh', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'National Taiwan University', 'TW', 2026, 'active'),
  ('X06259002', 'Darren Lim Jun Wei', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'National University of Singapore', 'SG', 2025, 'active'),
  ('X06259003', 'Zhang Wei', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Xiamen University', 'CN', 2025, 'active'),
  ('X05259004', 'Leon Wagner', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Technische Hochschule Deggendorf', 'DE', 2025, 'active'),
  ('X05269005', 'Nicole Ong Hui Min', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Temasek Polytechnic', 'SG', 2026, 'active'),
  -- 10_kegiatan_tambahan_2
  ('B12239256', 'Ignatius Lim', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12259675', 'Irvan Effendi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12259921', 'Hendrik Suryadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12249585', 'Yemima Effendi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2024, 'active'),
  ('B12229628', 'Bryan Jayadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2022, 'active'),
  ('B12259849', 'Kristina Tanuwijaya', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12239294', 'Glory Effendi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12239153', 'Samuel Prawira', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12249412', 'Valencia Budiman', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2024, 'active'),
  ('B12259553', 'Raymond Wijaya', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12259448', 'Irvan Lim', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12239792', 'Angela Pangestu', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12249256', 'Elisabeth Kusnadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2024, 'active'),
  ('B12249376', 'Nicholas Sutanto', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2024, 'active'),
  ('B12239075', 'Elisabeth Hadinata', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B14239757', 'Calvin Tedja', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2023, 'active'),
  ('B14229309', 'Kenneth Kartika', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2022, 'active'),
  ('B14239830', 'Lukas Lim', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2023, 'active'),
  ('B14229407', 'Kristina Rusli', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2022, 'active'),
  ('B14259358', 'Samuel Kusnadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2025, 'active'),
  ('B14229541', 'Agnes Santoso', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2022, 'active'),
  ('B14249427', 'Joanne Halim', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2024, 'active'),
  ('B14249899', 'Hendrik Budiman', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2024, 'active'),
  ('B14259010', 'Natasha Halim', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2025, 'active'),
  ('B14229977', 'Jessica Budiman', 'B', 'Fakultas Teknologi Industri', 'Teknik Mesin', 'regular', null, null, 2022, 'active'),
  ('X06269006', 'Hannah Schulz', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Technische Hochschule Deggendorf', 'DE', 2026, 'active'),
  ('X05269007', 'Chloe Mitchell', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Melbourne', 'AU', 2026, 'active'),
  ('X05269008', 'Min-seo Yoon', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Yonsei University', 'KR', 2026, 'active'),
  ('X06269009', 'Yuto Ishikawa', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Kanazawa Institute of Technology', 'JP', 2026, 'active'),
  ('X06269010', 'Aisyah binti Hamzah', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Universiti Teknologi Malaysia', 'MY', 2026, 'active'),
  -- 10_kegiatan_tambahan_3
  ('D32249150', 'Steven Rusli', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32259472', 'Kevin Rusli', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2025, 'active'),
  ('D32249331', 'Fransiska Wijaya', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32229204', 'Adrian Prawira', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2022, 'active'),
  ('D32239758', 'Amanda Hartanto', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32249505', 'Felix Chandra', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32259900', 'Wendy Budiman', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2025, 'active'),
  ('D32229279', 'Fiona Wibisono', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2022, 'active'),
  ('D32249196', 'Clara Sutanto', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32259976', 'Darren Gunawan', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2025, 'active'),
  ('D32249493', 'Karina Prawira', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32229661', 'Samuel Budiman', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2022, 'active'),
  ('D32239572', 'Felix Hartanto', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32239508', 'Samuel Rusli', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32259984', 'Karina Wijaya', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2025, 'active'),
  ('D31249692', 'Gilbert Wijaya', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31239726', 'Ricky Chandra', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31229821', 'Yemima Hartanto', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31229027', 'Irvan Budiman', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31229451', 'Alvin Kartika', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31239549', 'Nicholas Angkasa', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249207', 'Raymond Kartika', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31259757', 'Bryan Hadinata', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2025, 'active'),
  ('D31249746', 'Bella Tanuwijaya', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31239185', 'Joanne Santoso', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('X06269011', 'Lachlan Reid', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Monash University', 'AU', 2026, 'active'),
  ('X06269012', 'Lim Wei Jie', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Taylor''s University', 'MY', 2026, 'active'),
  ('X05259013', 'Nur Hazwani binti Yusof', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Universiti Brunei Darussalam', 'BN', 2025, 'active'),
  ('X05259014', 'Zoe Campbell', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Curtin University', 'AU', 2025, 'active'),
  ('X06259015', 'Ji-woo Shin', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Yonsei University', 'KR', 2025, 'active'),
  -- 10_kegiatan_tambahan_4
  ('D31259442', 'Michelle Angkasa', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2025, 'active'),
  ('D31239083', 'Joanne Chandra', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31229852', 'Gilbert Angkasa', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31239791', 'Kenneth Sutanto', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249994', 'Kenneth Pangestu', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31239881', 'Evan Pangestu', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31229748', 'Calvin Kartika', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31239043', 'Priscilla Kartika', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31239676', 'Joshua Jayadi', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249546', 'Joanne Tan', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31249493', 'Kevin Lukito', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31249971', 'Joanne Tedja', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31249923', 'Joshua Susilo', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31249797', 'Matthew Rusli', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31239469', 'Vincent Soetomo', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31229309', 'Raymond Jayadi', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31259588', 'Ricky Kusnadi', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2025, 'active'),
  ('D31249029', 'Albert Kusnadi', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31239820', 'Karina Rusli', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249725', 'Samuel Lukito', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('H71249141', 'Aurelia Hadinata', 'H', 'School of Business and Management', 'Magister Manajemen', 'regular', null, null, 2024, 'active'),
  ('H71249876', 'Hana Halim', 'H', 'School of Business and Management', 'Magister Manajemen', 'regular', null, null, 2024, 'active'),
  ('H71249078', 'Ricky Pangestu', 'H', 'School of Business and Management', 'Magister Manajemen', 'regular', null, null, 2024, 'active'),
  ('H71259136', 'Carissa Budiman', 'H', 'School of Business and Management', 'Magister Manajemen', 'regular', null, null, 2025, 'active'),
  ('H71259686', 'Felix Soetomo', 'H', 'School of Business and Management', 'Magister Manajemen', 'regular', null, null, 2025, 'active'),
  ('X05259016', 'Thanakorn Chaiwat', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Chulalongkorn University', 'TH', 2025, 'active'),
  ('X06259017', 'Chen-wei Lo', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'National Taiwan University', 'TW', 2025, 'active'),
  ('X05269018', 'Wong Ka Yan', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Hong Kong Baptist University', 'HK', 2026, 'active'),
  ('X05259019', 'Ananya Sharma', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Manipal Academy of Higher Education', 'IN', 2025, 'active'),
  ('X05259020', 'Thijs van Dijk', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Amsterdam', 'NL', 2025, 'active'),
  -- 10_kegiatan_tambahan_5
  ('C22259857', 'Fiona Darmawan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2025, 'active'),
  ('C22229994', 'Irvan Darmawan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2022, 'active'),
  ('C22239024', 'Nathania Lim', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2023, 'active'),
  ('C22249123', 'Debora Hartanto', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22249999', 'Raymond Effendi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22229438', 'Yemima Wijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2022, 'active'),
  ('C22239955', 'Kristina Santoso', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2023, 'active'),
  ('C22239188', 'Marcel Chandra', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2023, 'active'),
  ('C22249635', 'Valencia Halim', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22249514', 'Sharon Chandra', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22239208', 'Carissa Tan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2023, 'active'),
  ('C22249824', 'Yemima Tan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22239295', 'Joanne Wibisono', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2023, 'active'),
  ('C22249177', 'Joshua Soetomo', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2024, 'active'),
  ('C22229221', 'Gerald Kartika', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Interior', 'regular', null, null, 2022, 'active'),
  ('E42259904', 'Albert Pangestu', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2025, 'active'),
  ('E42249976', 'Kenneth Sanjaya', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2024, 'active'),
  ('E42239200', 'Darren Wijaya', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2023, 'active'),
  ('E42249697', 'Kenneth Prawira', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2024, 'active'),
  ('E42239001', 'Valencia Hadinata', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2023, 'active'),
  ('E42239798', 'Darren Pangestu', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2023, 'active'),
  ('E42249420', 'Felix Effendi', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2024, 'active'),
  ('E42239215', 'Steven Suryadi', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2023, 'active'),
  ('E42239743', 'Glory Rusli', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2023, 'active'),
  ('E42249210', 'Matthew Kartika', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Ilmu Komunikasi', 'regular', null, null, 2024, 'active'),
  ('X06259021', 'Paul Richter', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Hochschule Bremen', 'DE', 2025, 'active'),
  ('X05259022', 'Ruby Anderson', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Technology Sydney', 'AU', 2025, 'active'),
  ('X05259023', 'Rin Matsumoto', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Kanazawa Institute of Technology', 'JP', 2025, 'active'),
  ('X06259024', 'Muhammad Haziq bin Ali', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Universiti Brunei Darussalam', 'BN', 2025, 'active'),
  ('X05259025', 'Marcus Goh', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Temasek Polytechnic', 'SG', 2025, 'active'),
  -- 10_kegiatan_tambahan_6
  ('C21239954', 'Hana Gunawan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239549', 'Cynthia Tanuwijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21259848', 'Calvin Jayadi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21259343', 'Ricky Tedja', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21239991', 'Clara Effendi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239626', 'Edward Tan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239301', 'Matthew Wijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21249196', 'Kenneth Widjaja', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21249481', 'Irvan Angkasa', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21249147', 'Joanne Darmawan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21259948', 'Tiffany Suryadi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21259543', 'Joshua Santoso', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21239888', 'Valencia Gunawan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239659', 'Kevin Wibisono', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21249776', 'Vincent Setiadi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21229377', 'Alvin Tan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21259428', 'Gerald Angkasa', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21259142', 'Felix Santoso', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21229391', 'Felix Widjaja', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21239562', 'Natasha Jayadi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21249999', 'Raymond Wibisono', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21229931', 'Jovan Tanuwijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21249451', 'Steven Prawira', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21239724', 'Debora Susilo', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239896', 'Darren Rusli', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('X06269026', 'Hamish Clarke', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Technology Sydney', 'AU', 2026, 'active'),
  ('X06269027', 'Mia Robertson', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Technology Sydney', 'AU', 2026, 'active'),
  ('X05259028', 'Lena Koch', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Hochschule Bremen', 'DE', 2025, 'active'),
  ('X05259029', 'Abigail Vander Meer', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Calvin University', 'US', 2025, 'active'),
  ('X06269030', 'Nurul Izzah binti Rahim', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Taylor''s University', 'MY', 2026, 'active'),
  -- 10_kegiatan_tambahan_7
  ('B11229965', 'Nathania Kartika', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11239432', 'Owen Chandra', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11229081', 'Elisabeth Wijaya', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11259395', 'Owen Widjaja', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2025, 'active'),
  ('B11249182', 'Clara Setiadi', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B12239310', 'Vincent Lukito', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12249808', 'Yoel Lim', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2024, 'active'),
  ('B12259428', 'Felix Kartika', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12239803', 'Bella Widjaja', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12239093', 'Owen Kusnadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('D31239877', 'Darren Kartika', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31239764', 'Nathania Tan', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249852', 'Yoel Rusli', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D31229441', 'Steven Sanjaya', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31249140', 'Gilbert Sutanto', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D32239280', 'Darren Kusnadi', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32239903', 'Christian Rusli', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32249932', 'Karina Santoso', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32249413', 'Sharon Budiman', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32259676', 'Bryan Kusnadi', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2025, 'active'),
  ('C21229456', 'Agnes Soetomo', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21239107', 'Marcel Sanjaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21249850', 'Wendy Lukito', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('C21229874', 'Edward Wijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21239176', 'Samuel Tan', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('X06269031', 'Hui-min Tseng', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'National Taiwan University', 'TW', 2026, 'active'),
  ('X05269032', 'Siriporn Kaewmanee', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Chulalongkorn University', 'TH', 2026, 'active'),
  ('X06259033', 'Oscar Bennett', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Monash University', 'AU', 2025, 'active'),
  ('X05269034', 'Sota Fujimoto', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Kanazawa Institute of Technology', 'JP', 2026, 'active'),
  ('X05269035', 'Maximilian Braun', 'E', 'Fakultas Humaniora dan Industri Kreatif', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Hochschule Bremen', 'DE', 2026, 'active'),
  -- 10_kegiatan_tambahan_8
  ('B11239024', 'Karina Kartika', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11239809', 'Jessica Angkasa', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2023, 'active'),
  ('B11249208', 'Kristina Budiman', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2024, 'active'),
  ('B11229632', 'Adrian Darmawan', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B11229075', 'Nicholas Chandra', 'B', 'Fakultas Teknologi Industri', 'Informatika', 'regular', null, null, 2022, 'active'),
  ('B12259442', 'Kevin Suryadi', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2025, 'active'),
  ('B12239276', 'Vincent Prawira', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12239596', 'Alvin Hartanto', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12239147', 'Irvan Susilo', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('B12239970', 'Priscilla Santoso', 'B', 'Fakultas Teknologi Industri', 'Teknik Elektro', 'regular', null, null, 2023, 'active'),
  ('D31229599', 'Owen Gunawan', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2022, 'active'),
  ('D31239924', 'Kenneth Kusnadi', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31239267', 'Adrian Susilo', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31239013', 'Valencia Wijaya', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2023, 'active'),
  ('D31249008', 'Priscilla Hartanto', 'D', 'School of Business and Management', 'Manajemen', 'regular', null, null, 2024, 'active'),
  ('D32239187', 'Christian Soetomo', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32249796', 'Valencia Sanjaya', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32239589', 'Gerald Effendi', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2023, 'active'),
  ('D32249171', 'Joshua Hadinata', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2024, 'active'),
  ('D32229270', 'Amanda Soetomo', 'D', 'School of Business and Management', 'Akuntansi', 'regular', null, null, 2022, 'active'),
  ('C21229761', 'Tiffany Wijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2022, 'active'),
  ('C21259377', 'Stefanie Widjaja', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2025, 'active'),
  ('C21239657', 'Karina Jayadi', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21239466', 'Fiona Wijaya', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2023, 'active'),
  ('C21249938', 'Angela Tedja', 'C', 'Fakultas Humaniora dan Industri Kreatif', 'Desain Komunikasi Visual', 'regular', null, null, 2024, 'active'),
  ('X06269036', 'Sarah Teo Xin Yi', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'National University of Singapore', 'SG', 2026, 'active'),
  ('X05269037', 'Seung-hyun Baek', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Yonsei University', 'KR', 2026, 'active'),
  ('X06269038', 'Tan Mei Ling', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Taylor''s University', 'MY', 2026, 'active'),
  ('X06269039', 'Arif bin Zulkifli', 'B', 'Fakultas Teknologi Industri', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'Universiti Teknologi Malaysia', 'MY', 2026, 'active'),
  ('X06269040', 'Fleur de Jong', 'D', 'School of Business and Management', 'Program Pertukaran (Inbound)', 'inbound_exchange', 'University of Amsterdam', 'NL', 2026, 'active')
on conflict (nrp) do nothing;
