#!/usr/bin/env bash
# Builds supabase/deploy/sim-realisasi-supabase.sql: ONE file to paste into the Supabase SQL Editor
# (Dashboard -> SQL Editor -> New query -> paste -> Run). Same content and order as
# `scripts/db-deploy-supabase.sh --reset-realisasi`, with psql \ir includes inlined, wrapped in one transaction,
# and ending with the verification + schema fingerprint queries.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/deploy/sim-realisasi-supabase.sql"

inline() {  # print a SQL file, replacing "\ir <path>" lines with the referenced file (relative to the file)
  local f="$1" dir; dir="$(dirname "$f")"
  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" =~ ^[[:space:]]*\\ir[[:space:]]+(.+)$ ]]; then inline "$dir/${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^[[:space:]]*\\ ]]; then echo "unsupported psql meta-command in $f: $line" >&2; exit 1
    else printf '%s\n' "$line"; fi
  done < "$f"
}

{
  echo "-- SIM Realisasi -> SIM Kerjasama Supabase (simks-partnership): full install, generated by scripts/build-sql-bundle.sh"
  echo "-- commit $(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown). Paste into Supabase Dashboard -> SQL Editor -> Run."
  echo "-- One transaction: any error rolls everything back. Touches only schemas realisasi, kerjasama, mock_baak, mock_hr,"
  echo "-- the pg_cron job 'realisasi-daily-jobs' and realisasi_* migration-history rows. SIM Kerjasama tables are only read."
  echo "begin;"
  for f in "$ROOT/supabase/deploy/00_reset_realisasi.sql" "$ROOT"/supabase/migrations/*.sql "$ROOT"/supabase/seed-supabase/*.sql; do
    echo; echo "-- >>> ${f#"$ROOT"/}"; inline "$f"
  done
  echo; echo "commit;"
  echo
  echo "-- Verification (last result = schema fingerprint; must match docs/SUPABASE_INTEGRATION.md)"
  echo "select (select count(*) from realisasi.activities) as activities, (select count(*) from kerjasama.profiles) as accounts,"
  echo "       (select count(*) from kerjasama.documents) as documents_visible, (select count(*) from public.dokumen_kerja_sama) as simks_documents;"
  grep -v '^--' "$ROOT/supabase/deploy/fingerprint.sql"
} > "$OUT"
echo "wrote ${OUT#"$ROOT"/} ($(wc -c < "$OUT") bytes)"
